config/routes.rb
SalamanderServer::Application.routes.draw do

	match '/contact', :to => 'pages#contact'
	match '/about',   :to => 'pages#about'
	match '/help',    :to => 'pages#help'

  resources :categories

	resources :products

	root :to => "pages#home"

end

app/models/category.rb
# == Schema Information
# Schema version: 20110131014128
#
# Table name: categories
#
#  id         :integer(4)      not null, primary key
#  name       :string(255)
#  parent_id  :integer(4)
#  lft        :integer(4)
#  rgt        :integer(4)
#  depth      :integer(4)
#  html       :text
#  created_at :datetime
#  updated_at :datetime
#

class Category < ActiveRecord::Base
	acts_as_nested_set

	has_many :products

	attr_accessible :name, :html

	validates :name,	:presence => true,
										:length => { :maximum => 50 },
										:uniqueness => { :case_sensitive => false, :scope => :parent_id }

	def full_name
		category_tree = []
		self.self_and_ancestors.each { |v| category_tree << v.name }
		category_tree.join(", ")
	end

	def valid_parents
		if self.id.nil? then
			Category.all(:order => "lft")
		else
			valid_parents = []
			Category.all(:order => "lft").each { |v|
				valid_parents << v if ! v.is_or_is_descendant_of?(self)
			}
			valid_parents
		end
	end
	
	def Category.valid_parents(id)
		if id.nil? then
			Category.all(:order => "lft")
		else
			existing_category = Category.find(id)
			valid_parents = []
			Category.all(:order => "lft").each { |v|
				valid_parents << v if ! v.is_or_is_descendant_of?(existing_category)
			}
			valid_parents
		end
  end

  def Category.all_in_order
    self.all(:order => "lft")
  end

end

app/models/product.rb
# == Schema Information
# Schema version: 20110131014128
#
# Table name: products
#
#  id             :integer(4)      not null, primary key
#  name           :string(255)
#  category_id    :integer(4)
#  rank           :integer(4)      default(1)
#  default_price  :decimal(8, 2)
#  default_weight :decimal(6, 2)
#  html           :text
#  created_at     :datetime
#  updated_at     :datetime
#

class Product < ActiveRecord::Base

	belongs_to :category

	attr_accessible :name, :default_price, :default_weight, :html

	validates :name,	:presence => true,
										:length => { :maximum => 50 }
  validates_uniqueness_of :name, :scope => :category_id
	validates_associated :category
	validates_presence_of :category
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.xml
  def index
    @categories = Category.all(:order => "lft")
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.xml
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.xml
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.xml
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to(@category, :notice => 'Category was successfully created.') }
        format.xml  { render :xml => @category, :status => :created, :location => @category }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @category.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.xml
  def update

    @category = Category.find(params[:id])

		if params[:move]
			if params[:move] == 'up' and @category.left_sibling
				@left = @category.left_sibling
				@category.move_left
				redirect_to(categories_url)
			elsif params[:move] == 'down' and @category.right_sibling
				@category.move_right
				redirect_to(categories_url)
			else
				redirect_to(categories_url)
			end
		else
			respond_to do |format|
				if @category.update_attributes(params[:category])
					format.html { redirect_to(@category, :notice => 'Category was successfully updated.') }
					format.xml  { head :ok }
				else
					format.html { render :action => "edit" }
					format.xml  { render :xml => @category.errors, :status => :unprocessable_entity }
				end
			end
		end
  end

  # DELETE /categories/1
  # DELETE /categories/1.xml
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to(categories_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
		@title = 'Home'
  end

  def contact
		@title = 'Contact Us'
  end

	def about
		@title = 'About'
	end

	def help
		@title = 'Help'
	end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
		@title = "Products"
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
    @title = "Product \"" + @product.name + "\""
  end

  def new
		@title = "New Product"
    @product = Product.new
  end

  def edit
    @product = Product.find(params[:id])
  end

  def create
    @category = Category.find(params[:product][:category_id])
    @product = @category.products.build(params[:product])
    respond_to do |format|
      if @product.save
        format.html { redirect_to(products_path, :flash => { :success => 'Product was successfully created.' } ) }
        format.xml  { head :ok }
      else
        format.html { @title = "New Product"; render 'new' }
        format.xml  { render :xml => @product.errors, :status => :unprocessable_entity }
      end
    end
   end

  def update
    @product = Product.find(params[:id])
    @product.category = Category.find(params[:product][:category_id])
    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to(products_path, :flash => { :success => 'Product was successfully updated.' } ) }
        format.xml  { head :ok }
      else
        format.html { render 'edit' }
        format.xml  { render :xml => @product.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to(products_url, :notice => "Product was deleted") }
      format.xml  { head :ok }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

	# Return a title on a per-page basis.
	def title
		base_title = "Salamander Server"
		if @title.nil?
			base_title
		else
			"#{base_title} | #{@title}"
		end
	end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<div class="field">
    <%= f.label :parent_id %><br />
		<%= collection_select(:category, :parent_id, @category.valid_parents, :id, :full_name, {:include_blank => true}) %>
	</div>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :html %><br />
    <%= f.text_area :html %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<p id="notice"><%= notice %></p>

<table>
  <tr>
    <th>Name</th>
    <th>Html</th>
    <th>Action</th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= raw ("&nbsp;" * ((category.depth || 0) * 2)) %><%= link_to category.name, category %></td>
    <td><%= raw (category.html) %></td>
		<td>
			<%= form_tag category_path(category), { :method => 'put', :style => 'display:inline' } do -%>
				<%= hidden_field_tag 'move', 'up' %>
				<%= image_submit_tag 'arrow-up.gif', :alt => 'Move up' %>
			<% end -%>
			<%= form_tag category_path(category), { :method => 'put', :style => 'display:inline' } do -%>
				<%= hidden_field_tag 'move', 'down' %>
				<%= image_submit_tag 'arrow-down.gif', :alt => 'Move down' %>
			<% end -%>
			&nbsp;
			<%= link_to edit_category_path(category) do -%>
				<%= image_tag 'pencil.gif' %>
			<% end -%>
			<%= link_to(category, :confirm => 'Are you sure?', :method => :delete) do -%>
				<%= image_tag 'x-red.gif' %>
			<% end -%>
		</td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @category.full_name %>
</p>

<p>
  <b>Parent:</b>
  <%= @category.parent_id %>
</p>

<p>
  <b>Html:</b>
  <%= @category.html %>
</p>


<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/home/index.html.erb
<h1>Hello, Rails!</h1>
<ul>
	<li><%= link_to "Categories", categories_path %></li>
</ul>

app/views/layouts/_footer.html.erb
<footer>
	<nav class="round">
		<ul>
			<li><%= link_to "About", about_path %></li>
			<li><%= link_to "Contact", contact_path %></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header>
	<% logo = image_tag("logo.png", :alt => "Salamander") %>
	<%= link_to logo, root_path %>
	<nav class="round">
		<ul>
			<li><%= link_to "Home", root_path %></li>
			<li><%= link_to "Help", help_path %></li>
		</ul>
	</nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'screen', :media => 'screen' %>
<%= stylesheet_link_tag 'print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'ie', :media => 'screen' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>
<%= javascript_include_tag :defaults %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
  <%= csrf_meta_tag %>
	<%= render 'layouts/stylesheets' %>
</head>
<body>
    <div class="container">
        <%= render 'layouts/header' %>
        <section class="round">
            <% flash.each do |key, value| %>
                <div class="flash <%= key %>"><%= value %></div>
            <% end %>
            <%= yield %>
        </section>
        <%= render 'layouts/footer' %>
        <%= debug(params) if Rails.env.development? %>
    </div>
</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#About</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/help.html.erb
<h1>Pages#Help</h1>
<p>Find me in app/views/pages/help.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <%= render 'shared/error_messages' %>
  <div class="field">
    <%= f.label :category_id %><br />
    <%= f.collection_select :category_id, Category.all_in_order, :id, :full_name %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :default_price %><br />
    <%= f.text_field :default_price %>
  </div>
  <div class="field">
    <%= f.label :default_weight %><br />
    <%= f.text_field :default_weight %>
  </div>
  <div class="field">
    <%= f.label :html %><br />
    <%= f.text_area :html %>
  </div>
  <div class="actions">
    <%= f.submit "Save" %>
  </div>
<% end %>

app/views/products/create.html.erb
<h1>Products#create</h1>
<p>Find me in app/views/products/create.html.erb</p>

app/views/products/destroy.html.erb
<h1>Products#destroy</h1>
<p>Find me in app/views/products/destroy.html.erb</p>

app/views/products/edit.html.erb
<h1>Products#edit</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>

<table>
  <tr>
    <th>Category</th>
    <th>Name</th>
    <th>Price</th>
    <th>Action</th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= link_to product.category.full_name, product.category %></td>
    <td><%= link_to product.name, product %></td>
    <td><%= product.default_price %></td>
    <td>
        <%= link_to edit_product_path(product) do -%>
            <%= image_tag 'pencil.gif' %>
        <% end -%>
        <%= link_to(product, :confirm => 'Are you sure?', :method => :delete) do -%>
            <%= image_tag 'x-red.gif' %>
        <% end -%>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<div>
  <span class="label">Category</span>
  <span class="value"><%= @product.category.full_name %></span>
</div>

<div>
  <span class="label">Product</span>
  <span class="value"><%= @product.name %></span>
</div>

<div>
  <span class="label">Default price</span>
  <span class="value"><%= @product.default_price %></span>
</div>

<div>
  <span class="label">Default weight</span>
  <span class="value"><%= @product.default_weight %></span>
</div>

<div>
  <span class="label">Html</span>
  <span class="value"><%= @product.html %></span>
</div>

<div>
  <span class="label">Rank</span>
  <span class="value"><%= @product.rank %></span>
</div>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/products/update.html.erb
<h1>Products#update</h1>
<p>Find me in app/views/products/update.html.erb</p>

app/views/shared/_error_messages.html.erb
<% if @product.errors.any? %>
  <div id="errors_explanation">
    <h2>
      <%= pluralize(@product.errors.count, "error")  %>
      prohibited this product from being saved:
    </h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% @product.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>